name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install go-semantic-release
        uses: go-semantic-release/action@v1
        id: semantic_release
        with:
          github-token: ${{ secrets.GIT_TOKEN }}

      # - name: Check semantic-release output
      #   run: |
      #     echo "New version: ${{ steps.semantic_release.outputs.new_version }}"
      #     if [[ -z "${{ steps.semantic_release.outputs.new_version }}" ]]; then
      #       echo "No new version detected. Exiting..."
      #       exit 1
      #     fi

      # - name: Build and push Docker image
      #   # if: steps.semantic_release.outputs.new_release_published == 'true'
      #   run: |
      #     echo "New version: ${{ steps.semantic_release.outputs.new_version }}"
      #     set -x
      #     docker build -t likhithkanigolla/learn-docker-tags:${{ steps.semantic_release.outputs.new_version }} .
      #     docker build -t likhithkanigolla/learn-docker-tags:latest .
      #     docker push likhithkanigolla/learn-docker-tags:${{ steps.semantic_release.outputs.new_version }}
      #     docker push likhithkanigolla/learn-docker-tags:latest

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: . # Ensure this is the correct context
      #     file: ./Dockerfile
      #     push: true
      #     tags: likhithkanigolla/learn-docker-tags:${{ secrets.VERSION }}, likhithkanigolla/learn-docker-tags

      - name: Create GitHub Release
        if: steps.semantic_release.outputs.new_release_published == 'true'
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.semantic_release.outputs.new_version }}
          tag_name: ${{ steps.semantic_release.outputs.new_version }}
          body: |
            See the full release notes at: https://github.com/${{ github.repository }}/releases/tag/${{ steps.semantic_release.outputs.new_version }}
